version: 2
registries:
  github:
    type: git
    url: 'https://github.com/'
    username: 'x-access-token'
    password: '${{ secrets.DEPENDABOT_TOKEN }}'
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    registries:
      - 'github'
    commit-message:
      prefix: 'Update workflows & actions:'
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: 'gomod'
    directory: '/xk6-fido2'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'Update Go dependencies:'
    groups:
      go-dependencies:
        patterns:
          - "*"
