# Set update schedule for GitHub Actions

version: 2
registries:
  github: # GitHub registry for updating GitHub Actions
    type: git
    url: 'https://github.com/'
    username: 'x-access-token' # Not actually used but field required
    password: '${{ secrets.DEPENDABOT_TOKEN }}' # Preset dependabot token
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    registries:
      - 'github'
    commit-message:
      prefix: 'Update workflows & actions:'
    groups:
      github-actions:
        patterns:
          - "*"
