version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'Update workflows & actions:'
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: 'gomod'
    directory: '/xk6-fido2'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'Update Go dependencies:'
    groups:
      go-dependencies:
        patterns:
          - "*"
