name: PR workflow

on:
  pull_request:
    branches:
      - main
      - hotfix/*
      - feature/*
    types:
      - opened
      - synchronize

jobs:
  pr-build:
    uses: backbase-common/workflows/.github/workflows/java-maven-pull-request-legacy.yaml@24.3.0
    secrets:
      maven-username: ${{ secrets.REPO_DEPLOY_USR }}
      maven-password: ${{ secrets.REPO_DEPLOY_PWD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ACR_CLIENT_ID_SECRET: ${{ secrets.CORPSYSTEMS_ACR_CLIENT_ID_SECRET }}
      ACR_SECRET_PASSWORD: ${{ secrets.CORPSYSTEMS_ACR_SECRET_PASSWORD }}
      ACR_TENANT_ID_SECRET: ${{ secrets.CORPSYSTEMS_ACR_TENANT_ID_SECRET }}
