name: PR workflow

on:
  pull_request:
    branches:
      - main
      - hotfix/*
      - feature/*
    types:
      - opened
      - synchronize

jobs:
  pr-build:
    uses: backbase-common/workflows/.github/workflows/java-maven-pull-request.yaml@15.12.3
    secrets:
      maven-username: ${{ secrets.REPO_DEPLOY_USR }}
      maven-password: ${{ secrets.REPO_DEPLOY_PWD }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ACR_CLIENT_ID_SECRET: ${{ secrets.CORPSYSTEMS_ACR_CLIENT_ID_SECRET }}
      ACR_SECRET_PASSWORD: ${{ secrets.CORPSYSTEMS_ACR_SECRET_PASSWORD }}
      ACR_TENANT_ID_SECRET: ${{ secrets.CORPSYSTEMS_ACR_TENANT_ID_SECRET }}
      SECURITY_TOKEN: ${{ secrets.SECURITY_TOKEN }}
      SECURITY_TOOL_MTLS_CERT: ${{ secrets.SECURITY_TOOL_MTLS_CERT }}
      SECURITY_TOOL_MTLS_KEY: ${{ secrets.SECURITY_TOOL_MTLS_KEY }}
      SECURITY_TOOL_MTLS_PWD: ${{ secrets.SECURITY_TOOL_MTLS_PWD }}