name: Release workflow

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: xk6-fido2
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Run tests
        run: go test -v ./...

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build k6 binary with extension
        run: |
          cd ..
          xk6 build --with github.com/backbase-rnd/k6-fido2=./xk6-fido2 --output k6-fido2

      - name: Upload k6 binary
        uses: actions/upload-artifact@v4
        with:
          name: k6-fido2
          path: k6-fido2
